{
 "title": "Lustre LNET Router Health/Stats",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  { "title": "Health Metrics", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "LNET Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "alias": "$tag_host",
     "query": "select difference(errors)/60 from lnet_stats where $timeFilter GROUP BY host"
    }
   ]
  },
  {
   "title": "Network Timeouts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "alias": "$tag_host",
     "query": "select difference(network_timeout_count)/60 from lnet_stats where $timeFilter GROUP BY host"
    }
   ]
  },
  {
   "title": "LNET RPC Drops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "alias": "$tag_host",
     "query": "select difference(drop_count)/60 from lnet_stats where $timeFilter GROUP BY host"
    }
   ]
  },
  {
   "title": "LNET RPC Resend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "alias": "$tag_host",
     "query": "select difference(resend_count)/60 from lnet_stats where $timeFilter GROUP BY host"
    }
   ]
  },
  { "title": "Perf Metrics", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "LNET Read Perf (Aggregate Stacked)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$tag_host",
     "query": "select difference(port_rcv_data)/60 from infiniband where $timeFilter and device = 'mlx5_0'  and port = '1' and host =~ // GROUP BY host"
    }
   ]
  },
  {
   "title": "LNET Write Perf (Aggregate Stacked)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$tag_host",
     "query": "select difference(port_xmit_data)/60 from infiniband where $timeFilter and device = 'mlx5_0'  and port = '1' and host =~ // GROUP BY host"
    }
   ]
  }
 ]
}