{
 "title": "Lustre Project Quota",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project_name",
    "label": "project",
    "query": "SHOW TAG VALUES WITH KEY = \"project_name\""
   }
  ]
 },
 "panels": [
  {
   "title": "Project Statistics (Select in Drop Down) -- $project_name",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Project Block Usage Trend",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "alias": "Used Bytes",
     "measurement": "quota",
     "query": "SELECT \"kb_used\" FROM lustre_quota WHERE \"project_name\" =~ /^$project_name$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "blockused" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=", "value": "iccp" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "FILESET" },
      { "condition": "AND", "key": "fileset", "operator": "=~", "value": "/^$fileset$/" }
     ]
    },
    {
     "alias": "Quota Bytes",
     "measurement": "quota",
     "query": "SELECT \"kb_limit\" FROM lustre_quota WHERE \"project_name\" =~ /^$project_name$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "blockused" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=", "value": "iccp" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "FILESET" },
      { "condition": "AND", "key": "fileset", "operator": "=~", "value": "/^$fileset$/" }
     ]
    }
   ]
  },
  {
   "title": "Current Project Quota",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"kb_limit\") FROM lustre_quota WHERE \"project_name\" =~ /^$project_name$/ and $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Project iNode Usage Trend",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Used iNodes",
     "measurement": "quota",
     "query": "SELECT \"files\" FROM lustre_quota WHERE \"project_name\" =~ /^$project_name$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "filesused" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=", "value": "iccp" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$fileset$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "FILESET" }
     ]
    },
    {
     "alias": "Max iNodes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"file_limit\" FROM lustre_quota WHERE \"project_name\" =~ /^$project_name$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "iNodes Used (Project Total)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"files\") FROM lustre_quota WHERE \"project_name\" =~ /^$project_name$/ and $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Aggregate Lustre Quota Data", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Usage by Project",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_project_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select kb_used from lustre_quota where $timeFilter and project_id =~ /[0-9].*/ group by \"project_name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Project Capacity Consumption Over Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "alias": "$tag_project_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "quota",
     "query": "SELECT \"kb_used\" FROM lustre_quota WHERE $timeFilter and project_id =~ /[0-9].*/ GROUP BY \"project_name\"",
     "select": [
      [
       { "params": [ "blockused" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "FILESET" }
     ]
    }
   ]
  },
  {
   "title": "Usage by Project",
   "type": "table",
   "gridPos": { "h": 14, "w": 9, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "alias": "$tag_project_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select last(kb_used), last(kb_used)/last(kb_limit) from lustre_quota where $timeFilter and project_id =~ /[0-9].*/ group by \"project_name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Quota Utilization by Investment (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "$tag_project_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select kb_used/kb_limit from lustre_quota where $timeFilter and project_id =~ /[0-9].*/ group by \"project_name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average Project Quota Utilization",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 9, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "Usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(kb_used)/sum(kb_limit) from lustre_quota where $timeFilter and project_id =~ /[0-9].*/ group by time(5m)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Average Project Quota Utilization",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(kb_used)/sum(kb_limit) from lustre_quota where $timeFilter and project_id =~ /[0-9].*/ group by time(5m)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}