{
 "title": "Lustre Lustre Client Performance",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "client",
    "label": "Client",
    "query": "SHOW TAG VALUES WITH KEY = \"client\""
   },
   { "name": "fs", "label": "File System", "query": "dltahom0,dltascr0" },
   {
    "name": "mdop",
    "label": "Metadata Operation",
    "query": "open, close,getattr,getxattr,create,crossdir_rename,destroy,link,mkdir,mknod,rename,rmdir,samedir_rename,setattr,setxattr,statfs,sync,unlink"
   }
  ]
 },
 "panels": [
  { "title": "Client Performance for $client", "type": "text", "gridPos": { "h": 1, "w": 18, "x": 0, "y": 0 } },
  {
   "title": "Aggregate Cluster Read",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "select sum(ost_perf) from (select difference(read_bytes)/60  as ost_perf from lustre_client_perf where $timeFilter and fs =~ /$fs/ and disk_type = 'OST' group by disk,client) group by time(1m)"
    }
   ]
  },
  {
   "title": "Read Performance per OST",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$tag_disk",
     "query": "select difference(read_bytes)/60 from lustre_client_perf where $timeFilter and disk_type = 'OST' and client =~ /$client$/ and fs=~ /$fs/ group by disk"
    }
   ]
  },
  {
   "title": "Write Performance per OST",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$tag_disk",
     "query": "select difference(write_bytes)/60 from lustre_client_perf where $timeFilter and disk_type = 'OST' and client =~ /$client$/ and fs=~ /$fs/ group by disk"
    }
   ]
  },
  {
   "title": "Aggregate Cluster Write",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "select sum(ost_perf) from (select difference(write_bytes)/60  as ost_perf from lustre_client_perf where $timeFilter and fs =~ /$fs/ and disk_type = 'OST' group by disk,client) group by time(1m)"
    }
   ]
  },
  {
   "title": "Client Metadata Operation per MDT: $mdop",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_disk $mdop",
     "query": "select difference($mdop)/60 from lustre_client_perf where $timeFilter and disk_type = 'MDT' and client =~ /$client$/ and fs=~ /$fs/ group by disk"
    }
   ]
  },
  { "title": "Client Summary Stats", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Client Performance Now",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "query": "select sum(ost_read_perf),sum(ost_write_perf), sum(ost_read_calls), sum(ost_write_calls) from (select difference(read_bytes)/60 as ost_read_perf,  difference(write_bytes)/60 as ost_write_perf, difference(\"read\")/60 as ost_read_calls, difference(\"write\")/60 as ost_write_calls from lustre_client_perf where $timeFilter and fs =~ /$fs/ and disk_type = 'OST' group by disk,client) group by client,time(1m)"
    }
   ]
  },
  {
   "title": "Lustre Client Read Performance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$tag_client",
     "query": "select sum(ost_perf) from (select difference(read_bytes)/60  as ost_perf from lustre_client_perf where $timeFilter and fs =~ /$fs/ and disk_type = 'OST' group by disk,client) group by client,time(1m)"
    }
   ]
  },
  {
   "title": "Lustre Client Write Performance",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$tag_client",
     "query": "select sum(ost_perf) from (select difference(write_bytes)/60  as ost_perf from lustre_client_perf where $timeFilter and disk_type = 'OST' and fs =~ /$fs/ group by disk,client) group by client,time(1m)"
    }
   ]
  },
  {
   "title": "All Client Metadata Operation: $mdop",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_client",
     "query": "select sum(mdop) from (select difference($mdop)/60 as mdop from lustre_client_perf where $timeFilter and disk_type = 'MDT' and fs=~ /$fs/ group by disk) group by client,time(1m)"
    }
   ]
  }
 ]
}