{
 "title": "Lustre Group Quota",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "groupname",
    "label": "Group Name",
    "query": "SHOW TAG VALUES WITH KEY = \"group_name\""
   }
  ]
 },
 "panels": [
  {
   "title": "Group Statistics (Select in Drop Down) -- $groupname",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Group Block Usage Trend",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "alias": "Used Bytes",
     "measurement": "quota",
     "query": "SELECT \"kb_used\" FROM lustre_quota WHERE \"group_name\" =~ /^$groupname$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "blockused" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=", "value": "iccp" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "FILESET" },
      { "condition": "AND", "key": "fileset", "operator": "=~", "value": "/^$fileset$/" }
     ]
    }
   ]
  },
  {
   "title": "Group iNode Usage Trend",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Used iNodes",
     "measurement": "quota",
     "query": "SELECT \"files\" FROM lustre_quota WHERE \"group_name\" =~ /^$groupname$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "filesused" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=", "value": "iccp" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$fileset$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "FILESET" }
     ]
    }
   ]
  },
  { "title": "Aggregate Lustre Quota Data", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Usage by Group",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 8 },
   "format": "deckbytes",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_group_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select kb_used from lustre_quota where $timeFilter and group_id =~ /[0-9].*/ group by \"group_name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Group Capacity Consumption Over Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "alias": "$tag_group_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "quota",
     "query": "SELECT \"kb_used\" FROM lustre_quota WHERE $timeFilter and group_id =~ /[0-9].*/ GROUP BY \"group_name\"",
     "select": [
      [
       { "params": [ "blockused" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "FILESET" }
     ]
    }
   ]
  },
  {
   "title": "Usage by Group",
   "type": "table",
   "gridPos": { "h": 14, "w": 9, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "alias": "$tag_group_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select last(kb_used) from lustre_quota where $timeFilter and group_id =~ /[0-9].*/ group by \"group_name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average Group Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 9, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "alias": "Usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(kb_used) from lustre_quota where $timeFilter and group_id =~ /[0-9].*/ group by time(5m)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Average Group Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(kb_used) from lustre_quota where $timeFilter and group_id =~ /[0-9].*/ group by time(5m)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}