{
 "title": "Lustre File System Performance",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "name",
    "label": "Performance Metric",
    "query": "read_bytes, write_bytes, read_calls, write_calls"
   },
   {
    "name": "mdop",
    "label": "Metadata Operation",
    "query": "open,close,getattr,getxattr,mkdir,rmdir,rename,unlink,setattr,setxattr,statfs"
   }
  ]
 },
 "panels": [
  {
   "title": "Metadata Performance - Per MDT -- Operation: $mdop",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_name - $mdop",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select difference($mdop)/60 as \"mdoperation\" from lustre2 where $timeFilter group by \"name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Metadata Performance - Per MDT -- All Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_name - Metadata Operations",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select (difference(open)+difference(close)+difference(getattr)+difference(getxattr)+difference(mkdir)+difference(rmdir)+difference(rename)+ difference(unlink)+difference(setattr)+difference(setxattr)+difference(statfs))/60 from lustre2 where $timeFilter group by \"name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Lustre File System Performance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Write",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(lustre_write)/60 from (select difference(write_bytes) as \"lustre_write\" from lustre2 where $timeFilter group by \"name\") group by time(1m)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Read",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(lustre_read)/60 from (select difference(read_bytes) as \"lustre_read\" from lustre2 where $timeFilter group by \"name\") group by time(1m)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Read Calls",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(lustre_readc)/60 from (select difference(read_calls) as \"lustre_readc\" from lustre2 where $timeFilter group by \"name\") group by time(1m)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Write Calls",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(lustre_writec)/60 from (select difference(write_calls) as \"lustre_writec\" from lustre2 where $timeFilter group by \"name\") group by time(1m)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Lustre per MDS/OSS Server $name",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(lustre_perf)/60 from (select difference($name) as \"lustre_perf\" from lustre2 where $timeFilter group by \"name\") group by time(1m),host",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Lustre MDT/OST $name Performance Heat Map",
   "type": "heatmap",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(lustre_perf) from (select difference($name) as \"lustre_perf\" from lustre2 where $timeFilter group by \"name\") group by time(1m),\"name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}